version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fusion
      POSTGRES_PASSWORD: Metro@2025
      POSTGRES_DB: Metro
    ports:
      - "5432:5432"
    volumes:
      - /Users/mnyasambo/Metro Fusion/Apps/Metrodockerdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
